from sqlalchemy import JSON, ForeignKey, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, PKMixin, TenantScopedMixin, TimestampMixin


class Alert(Base, PKMixin, TenantScopedMixin, TimestampMixin):
    """A real-time, deterministic notification — low-stock alerts first
    (PD-009, PR-9). Generated by app/analytics/, never by AI.
    """

    __tablename__ = "alerts"

    alert_type: Mapped[str] = mapped_column(String(32), nullable=False)  # "low_stock" for now
    product_id: Mapped[object | None] = mapped_column(Uuid(as_uuid=True), ForeignKey("products.id"), nullable=True)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="active")
