from datetime import datetime

from sqlalchemy import DateTime, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, PKMixin, TenantScopedMixin, TimestampMixin


class Notification(Base, PKMixin, TenantScopedMixin, TimestampMixin):
    """The ORLA Notification Centre's one persisted row shape — every
    category (stock, uploads, reports, ORLA insights, team, billing,
    branches, ...) is the same table, distinguished only by `category`/
    `type_key`. Deliberately separate from Alert (app/models/alert.py,
    low-stock only, no read state, no UI) and from AuditLog (compliance/
    security trail, never customer-facing action prompts) — see the
    ORLA Notification Centre prompt's own "use audit logs for compliance,
    notifications for action prompts" principle. A notification is always
    generated by deterministic backend code (app/application/notifications.py)
    at an existing, already-tested trigger point; nothing here is ever
    written by AI.
    """

    __tablename__ = "notifications"

    category: Mapped[str] = mapped_column(String(32), nullable=False)
    type_key: Mapped[str] = mapped_column(String(64), nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)  # info | success | warning | critical
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    action_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # A relative in-app path only (e.g. "/products?business=..."), never an
    # arbitrary external URL — enforced by every notify_* call site always
    # building this from a fixed prefix, never from user/AI-generated text
    # (ORLA Notification Centre prompt: "action targets are safe app
    # routes, not arbitrary model-generated URLs").
    action_url: Mapped[str | None] = mapped_column(String(255), nullable=True)
    related_entity_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    related_entity_id: Mapped[object | None] = mapped_column(Uuid(as_uuid=True), nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="unread")  # unread | read | dismissed
    # Only ever "owner" or None today (Billing/Branches — a lapsed/renewed
    # subscription is the account owner's concern, not every staff
    # member's). None means visible to any role with a Membership on this
    # business, matching this app's existing default posture (e.g. alerts,
    # dashboard) — enforced in NotificationRepository's list query, never
    # trusted client-side.
    visible_to_role: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # Grouping/spam-control key (ORLA Notification Centre prompt's
    # "deterministic grouping key" requirement) — e.g. "low_stock_summary:
    # {business_id}". NULL for genuinely one-off events (an employee was
    # added, a report was generated) that should never collapse into an
    # earlier row. When set, notify() updates the existing open (non-
    # dismissed) row with this key instead of creating a duplicate.
    dedup_key: Mapped[str | None] = mapped_column(String(128), nullable=True, index=True)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
