"use client";

import { useEffect, useState } from "react";
import { AppNav } from "@/components/AppNav";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { apiGet, apiPost } from "@/lib/api/client";
import { businessDisplayLabel } from "@/lib/businessLabel";
import { useBusinessSelector } from "@/lib/hooks/useBusinessSelector";
import { broadcastNotificationsChanged } from "@/lib/notificationsBus";
import { useRequireSession } from "@/lib/supabase/useRequireSession";
import type { Notification, NotificationCategory, NotificationDateFilter, NotificationList } from "@/types";

const DATE_FILTER_LABELS: Record<NotificationDateFilter, string> = {
  today: "Today",
  "7d": "Last 7 days",
  "30d": "Last 30 days",
  custom: "Custom range",
};

const PAGE_SIZE = 25;

// The ORLA Notification Centre — one place for every category (stock,
// uploads, reports, ORLA insights, team, billing, branches, security &
// account) rather than a raw event log. Every row here was generated by
// deterministic backend code at a real trigger point (see
// backend/app/application/notifications.py) — this page only renders and
// lets the user manage read/dismissed state, never invents or summarizes
// anything itself.
const CATEGORY_LABELS: Record<NotificationCategory, string> = {
  stock: "Stock",
  data_uploads: "Data & Uploads",
  reports: "Reports",
  orla_insights: "ORLA Insights",
  team: "Team",
  billing: "Billing",
  branches: "Branches",
  security_account: "Security & Account",
};

const SEVERITY_LABELS: Record<string, string> = {
  info: "Info",
  success: "Success",
  warning: "Warning",
  critical: "Critical",
};

// Mirrors the backend's own visible_to_role="owner" set exactly
// (app/application/notifications.py — CATEGORY_TEAM/BILLING/BRANCHES,
// and the one CATEGORY_SECURITY_ACCOUNT type that's owner-only). The
// backend already blocks these rows for staff; this is purely UI
// polish so staff never sees a filter option that could only ever
// return nothing for them.
const OWNER_ONLY_CATEGORIES: NotificationCategory[] = ["team", "billing", "branches", "security_account"];

function timeAgo(value: string): string {
  return new Date(value).toLocaleString();
}

export default function NotificationsPage() {
  const { session, checkingSession } = useRequireSession();
  const { businesses, businessId, setBusinessId } = useBusinessSelector(session);

  const [items, setItems] = useState<Notification[]>([]);
  const [total, setTotal] = useState(0);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [confirmingDismiss, setConfirmingDismiss] = useState<Notification | null>(null);
  const [markingAll, setMarkingAll] = useState(false);

  const [categoryFilter, setCategoryFilter] = useState("");
  const [severityFilter, setSeverityFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState(""); // "" = active (unread + read), matching the backend default
  const [dateFilter, setDateFilter] = useState<NotificationDateFilter | "">("");
  // Only meaningful while dateFilter === "custom" — kept as separate draft
  // fields rather than committing on every keystroke, since a half-typed
  // date would otherwise fire an invalid request on each character.
  const [customStart, setCustomStart] = useState("");
  const [customEnd, setCustomEnd] = useState("");
  const [offset, setOffset] = useState(0);

  const business = businesses.find((b) => b.id === businessId);
  const isOwner = business?.role === "owner";
  const visibleCategoryEntries = Object.entries(CATEGORY_LABELS).filter(
    ([value]) => isOwner || !OWNER_ONLY_CATEGORIES.includes(value as NotificationCategory)
  );

  // If a non-owner somehow has an owner-only category selected (e.g. they
  // picked it while still resolving as owner, then switched to a business
  // where they're staff) — reset rather than silently keep querying a
  // filter value that could only ever come back empty for them.
  useEffect(() => {
    if (!isOwner && OWNER_ONLY_CATEGORIES.includes(categoryFilter as NotificationCategory)) {
      setCategoryFilter("");
    }
  }, [isOwner, categoryFilter]);

  // A custom range isn't ready to query until both ends are picked — while
  // only one is filled in, this stays false and the effect below simply
  // doesn't fire a (necessarily invalid, and pointlessly repeated) request.
  const customRangeReady = dateFilter !== "custom" || (customStart !== "" && customEnd !== "");

  function load(id: string, currentOffset: number) {
    setLoading(true);
    setError(null);
    const params = new URLSearchParams();
    if (categoryFilter) params.set("category", categoryFilter);
    if (severityFilter) params.set("severity", severityFilter);
    if (statusFilter) params.set("status", statusFilter);
    if (dateFilter) params.set("date_filter", dateFilter);
    if (dateFilter === "custom") {
      params.set("start_date", customStart);
      params.set("end_date", customEnd);
    }
    params.set("limit", String(PAGE_SIZE));
    params.set("offset", String(currentOffset));
    apiGet<NotificationList>(`/businesses/${id}/notifications?${params.toString()}`)
      .then((result) => {
        setItems(result.items);
        setTotal(result.total);
        setUnreadCount(result.unread_count);
      })
      .catch(() => {
        // Found live: a failed fetch left the *previous* business/filter's
        // items rendered underneath the error, which read as "these are
        // still current" when they might not be — clearing avoids a
        // notification centre showing possibly-stale unread state.
        setItems([]);
        setTotal(0);
        setError("Could not load notifications.");
      })
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    if (businessId && customRangeReady) load(businessId, offset);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [businessId, categoryFilter, severityFilter, statusFilter, dateFilter, customStart, customEnd, offset]);

  // Same convention as frontend/app/transactions/page.tsx: each filter
  // control resets offset itself (not a second effect keyed on the same
  // filters) — one page fetch per real change, not two.
  function updateFilter(setter: (value: string) => void, value: string) {
    setter(value);
    setOffset(0);
  }

  async function handleMarkRead(id: string) {
    setBusyId(id);
    try {
      const updated = await apiPost<Notification>(`/businesses/${businessId}/notifications/${id}/read`, {});
      setItems((prev) => prev.map((n) => (n.id === id ? updated : n)));
      setUnreadCount((c) => Math.max(0, c - 1));
      broadcastNotificationsChanged();
    } catch {
      setError("Could not mark this notification as read.");
    } finally {
      setBusyId(null);
      setConfirmingDismiss(null);
    }
  }

  async function handleDismiss(id: string) {
    setBusyId(id);
    try {
      const wasUnread = items.find((n) => n.id === id)?.status === "unread";
      await apiPost<Notification>(`/businesses/${businessId}/notifications/${id}/dismiss`, {});
      setItems((prev) => (statusFilter === "dismissed" ? prev : prev.filter((n) => n.id !== id)));
      if (wasUnread) setUnreadCount((c) => Math.max(0, c - 1));
      broadcastNotificationsChanged();
    } catch {
      setError("Could not dismiss this notification.");
    } finally {
      setBusyId(null);
    }
  }

  async function handleMarkAllRead() {
    setMarkingAll(true);
    try {
      await apiPost<{ updated: number }>(`/businesses/${businessId}/notifications/mark-all-read`, {});
      setItems((prev) => prev.map((n) => (n.status === "unread" ? { ...n, status: "read" as const } : n)));
      setUnreadCount(0);
      broadcastNotificationsChanged();
    } catch {
      setError("Could not mark all notifications as read.");
    } finally {
      setMarkingAll(false);
    }
  }

  if (checkingSession) return <p>Loading…</p>;

  return (
    <main>
      <AppNav businessId={businessId} />
      <ConfirmDialog
        open={confirmingDismiss !== null}
        title="Dismiss this notification?"
        description="It will move to your dismissed notifications. If the underlying issue changes later, ORLA can create a new notification."
        confirmLabel="Dismiss notification"
        onCancel={() => setConfirmingDismiss(null)}
        onConfirm={() => confirmingDismiss && handleDismiss(confirmingDismiss.id)}
      />
      <div className="notifications-shell">
        <aside className="notifications-sidebar" aria-label="Notification filters">
          <label className="notifications-shop-label">
            Shop
            <select value={businessId} onChange={(e) => setBusinessId(e.target.value)}>
              {businesses.map((b) => (
                <option key={b.id} value={b.id}>{businessDisplayLabel(b)}</option>
              ))}
            </select>
          </label>
          <p className="notifications-filter-title">Categories</p>
          <div className="notifications-category-list">
            <button className="notifications-category" type="button" aria-pressed={categoryFilter === ""} onClick={() => updateFilter(setCategoryFilter, "")}>
              <span>All notifications</span><span className="notifications-category__count">{unreadCount || ""}</span>
            </button>
            {visibleCategoryEntries.map(([value, label]) => (
              <button key={value} className="notifications-category" type="button" aria-pressed={categoryFilter === value} onClick={() => updateFilter(setCategoryFilter, value)}>
                <span>{label}</span>
              </button>
            ))}
          </div>
        </aside>

        <div className="notifications-content">
          <div className="notifications-header">
            <div>
              <h1>Notification Centre</h1>
              <p className="hint">
                {isOwner
                  ? "Updates about stock, uploads, reports, insights, team, and billing, with a direct route to each next action."
                  : "Updates about your branch operations, with a direct route to each next action."}
              </p>
            </div>
            <button type="button" onClick={handleMarkAllRead} disabled={markingAll || unreadCount === 0}>
              Mark all read{unreadCount > 0 ? ` (${unreadCount})` : ""}
            </button>
          </div>

          {businessId && (
            <>
              <div className="notifications-toolbar">
                <label>
                  Severity
                  <select value={severityFilter} onChange={(e) => updateFilter(setSeverityFilter, e.target.value)}>
                    <option value="">All severities</option>
                    {Object.entries(SEVERITY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}
                  </select>
                </label>
                <label>
                  Status
                  <select value={statusFilter} onChange={(e) => updateFilter(setStatusFilter, e.target.value)}>
                    <option value="">Unread &amp; read</option>
                    <option value="unread">Unread only</option>
                    <option value="read">Read only</option>
                    <option value="dismissed">Dismissed</option>
                  </select>
                </label>
                <label>
                  Date
                  <select value={dateFilter} onChange={(e) => {
                    const next = e.target.value as NotificationDateFilter | "";
                    setDateFilter(next);
                    if (next !== "custom") { setCustomStart(""); setCustomEnd(""); }
                    setOffset(0);
                  }}>
                    <option value="">All time</option>
                    {Object.entries(DATE_FILTER_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}
                  </select>
                </label>
                {dateFilter === "custom" && <>
                  <label>From<input type="date" value={customStart} max={customEnd || undefined} onChange={(e) => updateFilter(setCustomStart, e.target.value)} /></label>
                  <label>To<input type="date" value={customEnd} min={customStart || undefined} onChange={(e) => updateFilter(setCustomEnd, e.target.value)} /></label>
                </>}
              </div>

              {error && <div className="notifications-feedback status-error">{error} <button type="button" onClick={() => load(businessId, offset)}>Retry</button></div>}
              {dateFilter === "custom" && !customRangeReady && <p className="hint">Pick both a start and end date to apply the custom range.</p>}
              {loading ? <div className="notifications-empty">Loading...</div> : items.length === 0 ? (
                <div className="notifications-empty">No notifications to show{statusFilter || categoryFilter || severityFilter || dateFilter ? " for this filter." : "."}</div>
              ) : (
                <>
                  <ul className="notifications-list">
                    {items.map((n) => (
                      <li key={n.id} className={`notification-card${n.status === "unread" ? " notification-card--unread" : ""}`}>
                        <span className={`notification-card__severity notification-card__severity--${n.severity}`} aria-label={`${SEVERITY_LABELS[n.severity] ?? n.severity} notification`} />
                        <div>
                          <div className="notification-card__title-row">
                            <strong className="notification-card__title">{n.title}</strong>
                            <span className="notification-card__tag">{CATEGORY_LABELS[n.category] ?? n.category}</span>
                          </div>
                          <p className="notification-card__meta">{SEVERITY_LABELS[n.severity] ?? n.severity} · {timeAgo(n.created_at)}</p>
                          <p className="notification-card__body">{n.body}</p>
                          {n.action_url && n.action_label && <a className="notification-card__action-link" href={`${n.action_url}${n.action_url.includes("?") ? "&" : "?"}business=${businessId}`}>{n.action_label}</a>}
                        </div>
                        <div className="notification-card__controls">
                          {n.status === "unread" && <button className="notification-card__control" type="button" disabled={busyId === n.id} onClick={() => handleMarkRead(n.id)}>Mark read</button>}
                          {n.status !== "dismissed" && <button className="notification-card__control" type="button" disabled={busyId === n.id} onClick={() => setConfirmingDismiss(n)}>Dismiss</button>}
                        </div>
                      </li>
                    ))}
                  </ul>
                  <nav className="notifications-pagination" aria-label="Notification pages">
                    <button type="button" disabled={offset === 0 || loading} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}>Previous</button>
                    <span aria-live="polite">{Math.min(offset + 1, total)}-{Math.min(offset + PAGE_SIZE, total)} of {total}</span>
                    <button type="button" disabled={offset + PAGE_SIZE >= total || loading} onClick={() => setOffset(offset + PAGE_SIZE)}>Next</button>
                  </nav>
                </>
              )}
            </>
          )}
        </div>
      </div>
    </main>
  );
}
