"use client";

import { useEffect, useState } from "react";
import { AppNav } from "@/components/AppNav";
import { apiGet, apiPost } from "@/lib/api/client";
import { useBusinessSelector } from "@/lib/hooks/useBusinessSelector";
import { useRequireSession } from "@/lib/supabase/useRequireSession";
import type { Notification, NotificationCategory, NotificationList } from "@/types";

// The ORLA Notification Centre — one place for every category (stock,
// uploads, reports, ORLA insights, team, billing, branches, security &
// account) rather than a raw event log. Every row here was generated by
// deterministic backend code at a real trigger point (see
// backend/app/application/notifications.py) — this page only renders and
// lets the user manage read/dismissed state, never invents or summarizes
// anything itself.
const CATEGORY_LABELS: Record<NotificationCategory, string> = {
  stock: "Stock",
  data_uploads: "Data & Uploads",
  reports: "Reports",
  orla_insights: "ORLA Insights",
  team: "Team",
  billing: "Billing",
  branches: "Branches",
  security_account: "Security & Account",
};

const SEVERITY_LABELS: Record<string, string> = {
  info: "Info",
  success: "Success",
  warning: "Warning",
  critical: "Critical",
};

function timeAgo(value: string): string {
  return new Date(value).toLocaleString();
}

export default function NotificationsPage() {
  const { session, checkingSession } = useRequireSession();
  const { businesses, businessId, setBusinessId } = useBusinessSelector(session);

  const [items, setItems] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [markingAll, setMarkingAll] = useState(false);

  const [categoryFilter, setCategoryFilter] = useState("");
  const [severityFilter, setSeverityFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState(""); // "" = active (unread + read), matching the backend default

  function load(id: string) {
    setLoading(true);
    setError(null);
    const params = new URLSearchParams();
    if (categoryFilter) params.set("category", categoryFilter);
    if (severityFilter) params.set("severity", severityFilter);
    if (statusFilter) params.set("status", statusFilter);
    const query = params.toString() ? `?${params.toString()}` : "";
    apiGet<NotificationList>(`/businesses/${id}/notifications${query}`)
      .then((result) => {
        setItems(result.items);
        setUnreadCount(result.unread_count);
      })
      .catch(() => setError("Could not load notifications."))
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    if (businessId) load(businessId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [businessId, categoryFilter, severityFilter, statusFilter]);

  async function handleMarkRead(id: string) {
    setBusyId(id);
    try {
      const updated = await apiPost<Notification>(`/businesses/${businessId}/notifications/${id}/read`, {});
      setItems((prev) => prev.map((n) => (n.id === id ? updated : n)));
      setUnreadCount((c) => Math.max(0, c - 1));
    } catch {
      setError("Could not mark this notification as read.");
    } finally {
      setBusyId(null);
    }
  }

  async function handleDismiss(id: string) {
    setBusyId(id);
    try {
      const wasUnread = items.find((n) => n.id === id)?.status === "unread";
      await apiPost<Notification>(`/businesses/${businessId}/notifications/${id}/dismiss`, {});
      setItems((prev) => (statusFilter === "dismissed" ? prev : prev.filter((n) => n.id !== id)));
      if (wasUnread) setUnreadCount((c) => Math.max(0, c - 1));
    } catch {
      setError("Could not dismiss this notification.");
    } finally {
      setBusyId(null);
    }
  }

  async function handleMarkAllRead() {
    setMarkingAll(true);
    try {
      await apiPost<{ updated: number }>(`/businesses/${businessId}/notifications/mark-all-read`, {});
      setItems((prev) => prev.map((n) => (n.status === "unread" ? { ...n, status: "read" as const } : n)));
      setUnreadCount(0);
    } catch {
      setError("Could not mark all notifications as read.");
    } finally {
      setMarkingAll(false);
    }
  }

  if (checkingSession) return <p>Loading…</p>;

  return (
    <main>
      <AppNav businessId={businessId} />
      <h1>Notification Centre</h1>
      <p className="hint">
        Everything ORLA thinks you should know about — stock, uploads, reports, insights, team, and billing — in one
        place. Each notification links straight to the page it's about.
      </p>

      <label>
        Shop
        <select value={businessId} onChange={(e) => setBusinessId(e.target.value)}>
          {businesses.map((b) => (
            <option key={b.id} value={b.id}>
              {b.name}
            </option>
          ))}
        </select>
      </label>

      {businessId && (
        <>
          <div>
            <label>
              Category
              <select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}>
                <option value="">All categories</option>
                {Object.entries(CATEGORY_LABELS).map(([value, label]) => (
                  <option key={value} value={value}>
                    {label}
                  </option>
                ))}
              </select>
            </label>
            {" "}
            <label>
              Severity
              <select value={severityFilter} onChange={(e) => setSeverityFilter(e.target.value)}>
                <option value="">All severities</option>
                {Object.entries(SEVERITY_LABELS).map(([value, label]) => (
                  <option key={value} value={value}>
                    {label}
                  </option>
                ))}
              </select>
            </label>
            {" "}
            <label>
              Status
              <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
                <option value="">Unread &amp; read</option>
                <option value="unread">Unread only</option>
                <option value="read">Read only</option>
                <option value="dismissed">Dismissed</option>
              </select>
            </label>
            {" "}
            <button type="button" onClick={handleMarkAllRead} disabled={markingAll || unreadCount === 0}>
              Mark all read ({unreadCount} unread)
            </button>
          </div>

          {error && <p className="status-error">{error}</p>}
          {loading ? (
            <p>Loading…</p>
          ) : items.length === 0 ? (
            <p>No notifications to show{statusFilter || categoryFilter || severityFilter ? " for this filter." : "."}</p>
          ) : (
            <ul>
              {items.map((n) => (
                <li key={n.id} className={n.status === "unread" ? "status-unread" : undefined}>
                  <strong>{n.title}</strong> — <span>{SEVERITY_LABELS[n.severity] ?? n.severity}</span>
                  {" · "}
                  <span>{CATEGORY_LABELS[n.category] ?? n.category}</span>
                  {" · "}
                  <span>{timeAgo(n.created_at)}</span>
                  <p>{n.body}</p>
                  {n.action_url && n.action_label && (
                    <a href={`${n.action_url}${n.action_url.includes("?") ? "&" : "?"}business=${businessId}`}>
                      {n.action_label}
                    </a>
                  )}
                  {" "}
                  {n.status === "unread" && (
                    <button type="button" disabled={busyId === n.id} onClick={() => handleMarkRead(n.id)}>
                      Mark read
                    </button>
                  )}
                  {n.status !== "dismissed" && (
                    <button type="button" disabled={busyId === n.id} onClick={() => handleDismiss(n.id)}>
                      Dismiss
                    </button>
                  )}
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </main>
  );
}
